AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

# Layout
Layout/LineLength:
  Max: 120

# Style
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 200

# Lint
Lint/UnusedMethodArgument:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true
